[2024-04-16T11:57:44.004+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T11:57:44.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T11:57:44.029+0000] {logging_mixin.py:188} INFO - [2024-04-16T11:57:44.029+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T11:58:00.664+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T11:58:01.052+0000] {logging_mixin.py:188} INFO - [2024-04-16T11:58:01.048+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T11:58:01.105+0000] {logging_mixin.py:188} INFO - [2024-04-16T11:58:01.104+0000] {dag.py:3954} INFO - Setting next_dagrun for get_data_dag to 2024-04-15 00:00:00+00:00, run_after=2024-04-16 00:00:00+00:00
[2024-04-16T11:58:01.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data_dag.py took 17.198 seconds
[2024-04-16T11:58:32.576+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T11:58:32.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T11:58:32.598+0000] {logging_mixin.py:188} INFO - [2024-04-16T11:58:32.593+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T11:58:40.115+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T11:58:40.387+0000] {logging_mixin.py:188} INFO - [2024-04-16T11:58:40.378+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T11:58:40.446+0000] {logging_mixin.py:188} INFO - [2024-04-16T11:58:40.445+0000] {dag.py:3954} INFO - Setting next_dagrun for get_data_dag to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-16T11:58:40.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data_dag.py took 8.023 seconds
[2024-04-16T12:08:34.556+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:08:34.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:08:34.572+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:08:34.572+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:08:44.360+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:08:44.673+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:08:44.664+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T12:08:44.759+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:08:44.758+0000] {dag.py:3954} INFO - Setting next_dagrun for get_data_dag to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-16T12:08:44.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data_dag.py took 10.323 seconds
[2024-04-16T12:09:15.071+0000] {processor.py:161} INFO - Started process (PID=105) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:09:15.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:09:15.075+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:09:15.074+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:09:16.164+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:09:16.180+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:09:16.180+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T12:09:16.202+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:09:16.202+0000] {dag.py:3954} INFO - Setting next_dagrun for get_data_dag to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-16T12:09:16.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data_dag.py took 1.172 seconds
[2024-04-16T12:09:46.521+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:09:46.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:09:46.524+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:09:46.524+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:09:47.241+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:09:47.257+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:09:47.256+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T12:09:47.275+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:09:47.275+0000] {dag.py:3954} INFO - Setting next_dagrun for get_data_dag to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-16T12:09:47.293+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data_dag.py took 0.781 seconds
[2024-04-16T12:10:17.641+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:10:17.653+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:10:17.667+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:10:17.665+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:10:21.110+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:31:07.304+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:31:07.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:31:07.312+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:31:07.311+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:31:25.494+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:31:25.880+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:31:25.878+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T12:31:25.935+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:31:25.934+0000] {dag.py:3954} INFO - Setting next_dagrun for get_data_dag to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-16T12:31:26.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data_dag.py took 18.748 seconds
[2024-04-16T12:31:56.577+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:31:56.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:31:56.583+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:31:56.582+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:31:57.230+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:31:57.247+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:31:57.247+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T12:31:57.271+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:31:57.270+0000] {dag.py:3954} INFO - Setting next_dagrun for get_data_dag to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-16T12:31:57.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data_dag.py took 0.721 seconds
[2024-04-16T12:32:28.177+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:32:28.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:32:28.179+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:32:28.179+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:32:28.749+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:32:28.762+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:32:28.762+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T12:32:28.780+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:32:28.779+0000] {dag.py:3954} INFO - Setting next_dagrun for get_data_dag to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-16T12:32:28.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data_dag.py took 0.626 seconds
[2024-04-16T12:32:59.499+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:32:59.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:32:59.501+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:32:59.500+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:33:00.048+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:33:00.062+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:33:00.061+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T12:33:00.080+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:33:00.080+0000] {dag.py:3954} INFO - Setting next_dagrun for get_data_dag to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-16T12:33:00.100+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data_dag.py took 0.608 seconds
[2024-04-16T12:33:30.379+0000] {processor.py:161} INFO - Started process (PID=303) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:33:30.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:33:30.382+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:33:30.381+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:33:31.410+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:33:31.429+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:33:31.429+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T12:33:31.460+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:33:31.459+0000] {dag.py:3954} INFO - Setting next_dagrun for get_data_dag to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-16T12:33:31.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data_dag.py took 1.122 seconds
[2024-04-16T12:34:01.681+0000] {processor.py:161} INFO - Started process (PID=366) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:34:01.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:34:01.685+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:34:01.685+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:34:04.243+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:34:04.323+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:34:04.322+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-04-16T12:34:04.368+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:34:04.368+0000] {dag.py:3954} INFO - Setting next_dagrun for get_data_dag to 2024-04-16 00:00:00+00:00, run_after=2024-04-17 00:00:00+00:00
[2024-04-16T12:34:04.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data_dag.py took 2.730 seconds
[2024-04-16T12:34:35.230+0000] {processor.py:161} INFO - Started process (PID=436) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:34:35.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:34:35.304+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:34:35.237+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:35:52.300+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:35:05.922+0000] {timeout.py:68} ERROR - Process timed out, PID: 436
[2024-04-16T12:38:18.004+0000] {processor.py:161} INFO - Started process (PID=525) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:38:18.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:38:18.020+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:38:18.013+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:38:56.482+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:38:56.481+0000] {timeout.py:68} ERROR - Process timed out, PID: 525
[2024-04-16T12:38:56.483+0000] {logging_mixin.py:188} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7fcedb6ed580>
[2024-04-16T12:38:56.484+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-04-16T12:38:56.485+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.12/weakref.py", line 369, in remove
[2024-04-16T12:38:56.486+0000] {logging_mixin.py:188} WARNING -     def remove(k, selfref=ref(self)):
[2024-04-16T12:38:56.487+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2024-04-16T12:38:56.487+0000] {logging_mixin.py:188} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2024-04-16T12:38:56.488+0000] {logging_mixin.py:188} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/get_data_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.9.0/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.9.0/best-practices.html#reducing-dag-complexity, PID: 525
[2024-04-16T12:38:58.845+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:40:15.975+0000] {processor.py:161} INFO - Started process (PID=595) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:40:15.977+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:40:15.978+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:40:15.978+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:40:47.640+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:40:46.693+0000] {timeout.py:68} ERROR - Process timed out, PID: 595
[2024-04-16T12:42:33.784+0000] {processor.py:161} INFO - Started process (PID=28) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:42:33.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:42:33.789+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:42:33.789+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:42:38.092+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:43:14.656+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 659, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 672, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/serialized_dag.py", line 158, in write_dag
    if session.scalar(
       ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-04-16T12:45:59.334+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:45:59.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data_dag.py for tasks to queue
[2024-04-16T12:45:59.338+0000] {logging_mixin.py:188} INFO - [2024-04-16T12:45:59.337+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_data_dag.py
[2024-04-16T12:46:02.117+0000] {processor.py:840} INFO - DAG(s) 'get_data_dag' retrieved from /opt/airflow/dags/get_data_dag.py
