[2024-04-15T14:58:46.669+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T14:58:46.869+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_data_dag.write_to_csv scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-15T14:58:46.897+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_data_dag.write_to_csv scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-15T14:58:46.899+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 6
[2024-04-15T14:58:46.965+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_to_csv> on 2024-04-12 00:00:00+00:00
[2024-04-15T14:58:47.011+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=823) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T14:58:47.013+0000] {standard_task_runner.py:63} INFO - Started process 825 to run task
[2024-04-15T14:58:47.031+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'get_data_dag', 'write_to_csv', 'scheduled__2024-04-12T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/get_data_dag.py', '--cfg-path', '/tmp/tmp6kod_d1g']
[2024-04-15T14:58:47.039+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask write_to_csv
[2024-04-15T14:58:48.551+0000] {task_command.py:426} INFO - Running <TaskInstance: get_data_dag.write_to_csv scheduled__2024-04-12T00:00:00+00:00 [running]> on host ead826da457c
[2024-04-15T14:58:48.897+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yazid' AIRFLOW_CTX_DAG_ID='get_data_dag' AIRFLOW_CTX_TASK_ID='write_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-12T00:00:00+00:00'
[2024-04-15T14:58:48.899+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T14:58:48.901+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T14:58:48.909+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: write_to_csv() missing 1 required positional argument: 'data'
[2024-04-15T14:58:48.941+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=get_data_dag, task_id=write_to_csv, execution_date=20240412T000000, start_date=20240415T145846, end_date=20240415T145848
[2024-04-15T14:58:48.996+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task write_to_csv (write_to_csv() missing 1 required positional argument: 'data'; 825)
[2024-04-15T14:58:49.060+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T14:58:49.146+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T14:58:49.163+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
