[2024-04-15T16:51:55.712+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T16:51:55.897+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_data_dag.write_to_csv scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-15T16:51:55.930+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_data_dag.write_to_csv scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-15T16:51:55.944+0000] {taskinstance.py:2303} INFO - Starting attempt 6 of 11
[2024-04-15T16:51:56.003+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_to_csv> on 2024-04-12 00:00:00+00:00
[2024-04-15T16:51:56.031+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=99) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T16:51:56.038+0000] {standard_task_runner.py:63} INFO - Started process 109 to run task
[2024-04-15T16:51:56.059+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'get_data_dag', 'write_to_csv', 'scheduled__2024-04-12T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/get_data_dag.py', '--cfg-path', '/tmp/tmp6d481aj8']
[2024-04-15T16:51:56.076+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask write_to_csv
[2024-04-15T16:51:56.572+0000] {task_command.py:426} INFO - Running <TaskInstance: get_data_dag.write_to_csv scheduled__2024-04-12T00:00:00+00:00 [running]> on host ead826da457c
[2024-04-15T16:51:57.255+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yazid' AIRFLOW_CTX_DAG_ID='get_data_dag' AIRFLOW_CTX_TASK_ID='write_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-12T00:00:00+00:00'
[2024-04-15T16:51:57.270+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T16:51:57.283+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T16:51:57.285+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: write_to_csv() missing 1 required positional argument: 'data'
[2024-04-15T16:51:57.312+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=get_data_dag, task_id=write_to_csv, execution_date=20240412T000000, start_date=20240415T165155, end_date=20240415T165157
[2024-04-15T16:51:57.352+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 66 for task write_to_csv (write_to_csv() missing 1 required positional argument: 'data'; 109)
[2024-04-15T16:51:57.403+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T16:51:57.480+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T16:51:57.497+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
