[2024-04-16T11:58:24.663+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T11:58:24.837+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: calculator_dag.generate_random_numbers scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-16T11:58:24.890+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: calculator_dag.generate_random_numbers scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-16T11:58:24.891+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-16T11:58:24.950+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_random_numbers> on 2024-04-15 00:00:00+00:00
[2024-04-16T11:58:24.974+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=58) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T11:58:24.982+0000] {standard_task_runner.py:63} INFO - Started process 64 to run task
[2024-04-16T11:58:24.972+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'calculator_dag', 'generate_random_numbers', 'scheduled__2024-04-15T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/calculator_dag.py', '--cfg-path', '/tmp/tmp8k4dm8lk']
[2024-04-16T11:58:24.991+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask generate_random_numbers
[2024-04-16T11:58:25.293+0000] {task_command.py:426} INFO - Running <TaskInstance: calculator_dag.generate_random_numbers scheduled__2024-04-15T00:00:00+00:00 [running]> on host 8054b3face16
[2024-04-16T11:58:25.666+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yazid' AIRFLOW_CTX_DAG_ID='calculator_dag' AIRFLOW_CTX_TASK_ID='generate_random_numbers' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-15T00:00:00+00:00'
[2024-04-16T11:58:25.669+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T11:58:25.677+0000] {python.py:237} INFO - Done. Returned value was: [20, 29, 19, 12, 35, 28, 45, 10, 3, 14, 48, 50, 38, 46, 13, 6, 2, 47, 4, 30, 44, 9, 43, 27, 5]
[2024-04-16T11:58:25.683+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T11:58:25.811+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=calculator_dag, task_id=generate_random_numbers, execution_date=20240415T000000, start_date=20240416T115824, end_date=20240416T115825
[2024-04-16T11:58:25.930+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T11:58:26.101+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-16T11:58:26.110+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
